### ISSUE TITLE
Update to 1.21 please?

### ISSUE THREAD

**Issue by DeeChael** [endorh/smart-completion#3]
As 1.21 has released for 40 days, I really really really want to use this powerful tool to type commands.
Will you update this mod to 1.21?
bcuz ur gradle build script is a lit bit confusing so I cant update to 1.21 by myself.

**Comment by endorh** [comment]
I'm glad you enjoy my mod, and I have good news for you, I had already updated it last Friday.
The only reason I hadn't published it yet was because I wanted to address #2 in the same release, but I can do that later in a bugfix release.

I've just published the release to [Curse Forge](https://www.curseforge.com/minecraft/mc-mods/smart-completion), and luckily it has been approved very fast (in the time I was writing this comment), so it's already available. ^^

**Comment by DeeChael** [comment]
thanks!
